// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9DouBYUsmbrv-5hB5E5nDSRZRui8ukEU',
    appId: '1:1042086449247:web:987619575de8300368cbea',
    messagingSenderId: '1042086449247',
    projectId: 'sports-field-booking-app',
    authDomain: 'sports-field-booking-app.firebaseapp.com',
    storageBucket: 'sports-field-booking-app.firebasestorage.app',
    measurementId: 'G-TE81FR2EKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6yy2Sm1vD0BAftuRx_HIMLld3mtK19E',
    appId: '1:1042086449247:android:9bd4f4091976a63868cbea',
    messagingSenderId: '1042086449247',
    projectId: 'sports-field-booking-app',
    storageBucket: 'sports-field-booking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIF6mIcl6IzxgnB8vxEcx8tWZJkSKfU9Y',
    appId: '1:1042086449247:ios:f5cdc0eb76b2e6d168cbea',
    messagingSenderId: '1042086449247',
    projectId: 'sports-field-booking-app',
    storageBucket: 'sports-field-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.testingFirebase26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIF6mIcl6IzxgnB8vxEcx8tWZJkSKfU9Y',
    appId: '1:1042086449247:ios:f5cdc0eb76b2e6d168cbea',
    messagingSenderId: '1042086449247',
    projectId: 'sports-field-booking-app',
    storageBucket: 'sports-field-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.testingFirebase26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9DouBYUsmbrv-5hB5E5nDSRZRui8ukEU',
    appId: '1:1042086449247:web:1ecf3c108887015568cbea',
    messagingSenderId: '1042086449247',
    projectId: 'sports-field-booking-app',
    authDomain: 'sports-field-booking-app.firebaseapp.com',
    storageBucket: 'sports-field-booking-app.firebasestorage.app',
    measurementId: 'G-NG6VBKBFTE',
  );
}
